apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-controller
  labels:
    app: simple-controller
rules:
  - verbs:
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - create
      - update
      - delete
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - persistentvolumeclaims
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
      - secrets
  - verbs:
      - get
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
  - verbs:
      - list
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
      - patch
    apiGroups:
      - simplecloud.app
    resources:
      - minecraftservers
      - minecraftservers/status
      - minecraftserversets
      - minecraftserversets/status
      - minecraftservergroups
      - minecraftservergroups/status
