apiVersion: apps/v1
kind: Deployment
metadata:
  name: strela-deployment
spec:
  selector:
    matchLabels:
      app: strela
  replicas: 1
  template:
    metadata:
      labels:
        app: strela
    spec:
      serviceAccountName: simple-controller
      containers:
      - name: default
        image: frederickbaier/strela
